//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCdbStokEntities : DbContext
    {
        public MVCdbStokEntities()
            : base("name=MVCdbStokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Table_1> M_Table_1 { get; set; }
        public virtual DbSet<S_Table_1> S_Table_1 { get; set; }
        public virtual DbSet<SAt_Table_1> SAt_Table_1 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<U_Table_1> U_Table_1 { get; set; }
    }
}
