//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Collections.Generic;


    public partial class U_Table_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public U_Table_1()
        {
            this.SAt_Table_1 = new HashSet<SAt_Table_1>();
        }
    
        public int URUNID { get; set; }
       
        public string URUNAD { get; set; }
       
        public string MARKA { get; set; }
        public Nullable<short> URUNKATAGORİ { get; set; }
        
        public Nullable<decimal> FİYAT { get; set; }
        public Nullable<byte> STOK { get; set; }
    
        public virtual S_Table_1 S_Table_1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAt_Table_1> SAt_Table_1 { get; set; }
    }
}
